language: php

php:
  - 5.6
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - docker run -d -p 8000:8000 centrifugo/centrifugo centrifugo --api_insecure

script:
  - vendor/bin/phpunit
